### ISSUE TITLE
Flake in Cortex tests

### ISSUE THREAD

**Issue by dbason** [rancher/opni#1159]
```
8:58PM INFO  actions.test._exec | panic: listen tcp 127.0.0.1:37415: bind: address already in use
8:58PM INFO  actions.test._exec | #25 1261.5
8:58PM INFO  actions.test._exec | #25 1261.5 goroutine 2051 [running]:
8:58PM INFO  actions.test._exec | #25 1261.5 github.com/rancher/opni/pkg/test.(*Environment).StartAgentDisconnectServer.func2.1()
8:58PM INFO  actions.test._exec | #25 1261.5 	/src/pkg/test/environment.go:1230 +0xa5
8:58PM INFO  actions.test._exec | #25 1261.5 created by github.com/rancher/opni/pkg/test.(*Environment).StartAgentDisconnectServer.func2
8:58PM INFO  actions.test._exec | #25 1261.5 	/src/pkg/test/environment.go:1227 +0xaf
8:58PM INFO  actions.test._exec | #25 1261.6 ginkgo run failed
8:58PM INFO  actions.test._exec | #25 1261.6   could not finalize profiles:
8:58PM INFO  actions.test._exec | #25 1261.6   Unable to read coverage file /src/test/integration/gateway/cover-integration.out:
8:58PM INFO  actions.test._exec | #25 1261.6   open /src/test/integration/gateway/cover-integration.out: no such file or directory
8:58PM INFO  actions.test._exec | #25 1261.6 exit status 1
```

There's a port conflict that should be investigated

**Comment by alexandreLamarre** [comment]
I think this is closed by https://github.com/rancher/opni/pull/1165
