### ISSUE TITLE
Intermittent issue with logging plugin

### ISSUE THREAD

**Issue by dbason** [rancher/opni#1200]
Occasionally the expected files are missing when a logging cluster is created which causes the plugin to crash

**Comment by dbason** [comment]
```
2023-03-19T21:39:40Z ERROR plugin.logging.opensearch-manager gateway/admin_v2.go:1011 failed to create client: secrets "opensearch-opni-internalopni" not found
--
Mon, Mar 20 2023 10:39:40 am | panic: secrets "opensearch-opni-internalopni" not found
Mon, Mar 20 2023 10:39:40 am |  
Mon, Mar 20 2023 10:39:40 am | goroutine 689 [running]:
Mon, Mar 20 2023 10:39:40 am | github.com/rancher/opni/plugins/logging/pkg/gateway.(*LoggingManagerV2).setOpensearchClient(0xc0007df0a0)
Mon, Mar 20 2023 10:39:40 am | github.com/rancher/opni/plugins/logging/pkg/gateway/admin_v2.go:1012 +0xc6d
Mon, Mar 20 2023 10:39:40 am | github.com/rancher/opni/plugins/logging/pkg/util.(*AsyncOpensearchClient).SetClient(0xc000da2450, 0xc000264f10)
Mon, Mar 20 2023 10:39:40 am | github.com/rancher/opni/plugins/logging/pkg/util/opensearch.go:41 +0xdc
Mon, Mar 20 2023 10:39:40 am | created by github.com/rancher/opni/plugins/logging/pkg/gateway.(*LoggingManagerV2).CreateOrUpdateOpensearchCluster
Mon, Mar 20 2023 10:39:40 am | github.com/rancher/opni/plugins/logging/pkg/gateway/admin_v2.go:181 +0x20a
```
