### ISSUE TITLE
Panic when creating snapshot

### ISSUE THREAD

**Issue by alexandreLamarre** [rancher/opni#1802]
Submitting a snapshot with :

![image](https://github.com/rancher/opni/assets/56211853/9d7d91f1-ef89-4765-ac5b-eb74f549077b)

I'm suspecting additional index is required

This is the request payload

UI payload : `snapshot10*/5**`

Gives the following panic:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xabd078]

goroutine 993 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
	go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:383 +0x25
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc001074000, {0x0, 0x0, 0x42a1d00?})
	go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:415 +0x975
panic({0x23ff520?, 0x4256c50?})
	runtime/panic.go:914 +0x21f
log/slog.(*Logger).Handler(...)
	log/slog/logger.go:89
log/slog.(*Logger).Enabled(0x0?, {0x2c68818?, 0x42d3e40?}, 0x10?)
	log/slog/logger.go:137 +0x18
log/slog.(*Logger).log(0x0, {0x2c68818, 0x42d3e40}, 0x8, {0x28b7dfb, 0x24}, {0x0, 0x0, 0x0})

```

### Fix 

restart gateway

**Comment by alexandreLamarre** [comment]
Also happens when name is unset

**Comment by dbason** [comment]
Issue will happen whenever there's an error (or anything that gets logged) because the logger is not set correctly.  The linked PR adds some verification around naming and fixes the logger along with an error in the reconciler.
